### ISSUE TITLE
Layout broke after the latest update

### ISSUE THREAD

**Issue by admlko** [walokra/Haikara#1]
Hi,

First of all, I rely on Haikara on every day basis.
So cheers to you for creating it!

However, after the latest update (0.9.8) the layout got broken with iPhone SE. I can only see about 3/4 of a settings page and my personal settings seems to be missing.

If you need further information, please ask.

**Comment by walokra** [comment]
Thanks for reporting the issue. I know the reason for it, just didn't test the new Settings screen on smaller screens enough. I'll fix it ASAP.

I forgot to add to the App Store text that due to the change how settings are stored they were resetted.

**Comment by admlko** [comment]
Thanks a lot!
